import {
  IconCardAthlete,
  IconCardCinema,
  IconCardStar,
} from "../../../components";

export const identitiesData = [
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardAthlete />,
    iconText: "Athlete",
    name: "Tom Brady",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardStar />,
    iconText: "Movie Star",
    name: "Meg Ryan",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardCinema />,
    iconText: "Athlete",
    name: "Tom Brady",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardStar />,
    iconText: "Movie Star",
    name: "Meg Ryan",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardAthlete />,
    iconText: "Athlete",
    name: "Tom Brady",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardStar />,
    iconText: "Movie Star",
    name: "Meg Ryan",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardCinema />,
    iconText: "Athlete",
    name: "Tom Brady",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardStar />,
    iconText: "Movie Star",
    name: "Meg Ryan",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardAthlete />,
    iconText: "Athlete",
    name: "Tom Brady",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardStar />,
    iconText: "Movie Star",
    name: "Meg Ryan",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardCinema />,
    iconText: "Athlete",
    name: "Tom Brady",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardStar />,
    iconText: "Movie Star",
    name: "Meg Ryan",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardAthlete />,
    iconText: "Athlete",
    name: "Tom Brady",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardStar />,
    iconText: "Movie Star",
    name: "Meg Ryan",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardCinema />,
    iconText: "Athlete",
    name: "Tom Brady",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardStar />,
    iconText: "Movie Star",
    name: "Meg Ryan",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardAthlete />,
    iconText: "Athlete",
    name: "Tom Brady",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardStar />,
    iconText: "Movie Star",
    name: "Meg Ryan",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardCinema />,
    iconText: "Athlete",
    name: "Tom Brady",
  },
  {
    date: "07/06",
    year: "2023",
    type: "Rare",
    icon: <IconCardStar />,
    iconText: "Movie Star",
    name: "Meg Ryan",
  },
];
